[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_port = COM3
monitor_port = COM3

lib_deps =
  bodmer/TFT_eSPI
  bblanchon/ArduinoJson
  tzapu/WiFiManager

build_flags =
  -DUSER_SETUP_LOADED=1
  -include "${PROJECT_DIR}/include/tft_setup.h"
